#!/bin/bash

LOG_FILE=~/Documents/log.txt

touch "$LOG_FILE"

if [ "$1" = "do" ]; then
  clear
  lines=$((($(tput lines) / 3) * 3))
  tail -n $lines $LOG_FILE
else
  echo $LOG_FILE | entr "$0" "do"
fi
